### ISSUE TITLE
publish documentation

### ISSUE THREAD

**Issue by brainrake** [mlabs-haskell/godot-cardano#37]
To make the developer experience smoother, we should publish documentation, eg. to github-pages.
See:
- https://www.mkdocs.org/
- https://github.com/GDQuest/gdscript-docs-maker
- https://flake.parts/options/hercules-ci-effects.html?highlight=github%20pages#opt-hercules-ci.github-pages.branch
- example: https://github.com/mlabs-haskell/cardano.nix/blob/main/docs/default.nix

**Comment by rmgaray** [comment]
This was closed by #62 . The docs don't render very well (there are issues with the brief description / description and links in general), but they are published indeed.
