### ISSUE TITLE
Add TxBuilder helpers for CIP68 minting

### ISSUE THREAD

**Issue by dfar-sga** [mlabs-haskell/godot-cardano#61]
Requires #56

**Comment by rmgaray** [comment]
In particular: we want to automatically generate CIP67 tags to liberate the user from encoding specifics. The user should be able to just provide a token name and the helpers should mint both the reference and the user NFT.

**Comment by rmgaray** [comment]
#56 already provided  helpers for minting CIP68 tokens.

It's worth mentioning that we still don't support reference inputs, so updating metadata is not something that can be done yet.
